# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8cd4f89d129578f0b688c6d222204050cc9d26e1a569d9a578fc1c1ad1815c3d7fe2a9b6b5be3c09b7c57bd1aebcf64efe33fe4f75a825a613300e8c77aa7aa

test:
  secret_key_base: 3c9b25fbacb1adea87f22fa480cdeddb5dcd9cfb18f2a6e1ab72907166b6107cf53be2c0f8d372e890f3f06d7c9b495ab2b7dc73ccac946247363433f3476b56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
